# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'creator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(650, 650)
        Form.setMinimumSize(QtCore.QSize(650, 650))
        Form.setMaximumSize(QtCore.QSize(650, 650))
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(70, 20, 512, 512))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(r"Pictures/ICON/BRAIN-DEV_1024_11_-_Copy.png"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(380, 600, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft Himalaya")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(220, 590, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-80, 50, 771, 141))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../Pictures/signature.png"))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Xemonay"))
        self.label_5.setText(_translate("Form", "Creator =>)"))
