# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'unscramble.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.answer2 = QtWidgets.QPushButton(self.centralwidget)
        self.answer2.setGeometry(QtCore.QRect(110, 450, 231, 81))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei Light")
        font.setPointSize(26)
        self.answer2.setFont(font)
        self.answer2.setObjectName("answer2")
        self.answer4 = QtWidgets.QPushButton(self.centralwidget)
        self.answer4.setGeometry(QtCore.QRect(450, 450, 231, 81))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei Light")
        font.setPointSize(26)
        self.answer4.setFont(font)
        self.answer4.setObjectName("answer4")
        self.count_lal = QtWidgets.QLabel(self.centralwidget)
        self.count_lal.setGeometry(QtCore.QRect(630, 30, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei Light")
        font.setPointSize(26)
        self.count_lal.setFont(font)
        self.count_lal.setObjectName("count_lal")
        self.timer = QtWidgets.QLabel(self.centralwidget)
        self.timer.setGeometry(QtCore.QRect(50, 30, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei Light")
        font.setPointSize(26)
        self.timer.setFont(font)
        self.timer.setObjectName("timer")
        self.answer3 = QtWidgets.QPushButton(self.centralwidget)
        self.answer3.setGeometry(QtCore.QRect(450, 340, 231, 81))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei Light")
        font.setPointSize(26)
        self.answer3.setFont(font)
        self.answer3.setObjectName("answer3")
        self.answer = QtWidgets.QLabel(self.centralwidget)
        self.answer.setGeometry(QtCore.QRect(110, 230, 571, 81))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei Light")
        font.setPointSize(36)
        self.answer.setFont(font)
        self.answer.setObjectName("answer")
        self.answer1 = QtWidgets.QPushButton(self.centralwidget)
        self.answer1.setGeometry(QtCore.QRect(110, 340, 231, 81))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei Light")
        font.setPointSize(26)
        self.answer1.setFont(font)
        self.answer1.setObjectName("answer1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.answer2.setText(_translate("MainWindow", "KCHEC"))
        self.answer4.setText(_translate("MainWindow", "KCHEC"))
        self.count_lal.setText(_translate("MainWindow", "0"))
        self.timer.setText(_translate("MainWindow", "00:00"))
        self.answer3.setText(_translate("MainWindow", "KCHEC"))
        self.answer.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">CHECK</p></body></html>"))
        self.answer1.setText(_translate("MainWindow", "KCHEC"))
