# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reaction.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.target_bt = QtWidgets.QPushButton(self.centralwidget)
        self.target_bt.setGeometry(QtCore.QRect(60, 520, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.target_bt.setFont(font)
        self.target_bt.setStyleSheet("background-color:#FF8A80;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.target_bt.setObjectName("target_bt")
        self.fa_target_bt_2 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_2.setGeometry(QtCore.QRect(30, 130, 31, 31))
        self.fa_target_bt_2.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_2.setText("")
        self.fa_target_bt_2.setObjectName("fa_target_bt_2")
        self.fa_target_bt_3 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_3.setGeometry(QtCore.QRect(120, 140, 31, 31))
        self.fa_target_bt_3.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_3.setText("")
        self.fa_target_bt_3.setObjectName("fa_target_bt_3")
        self.fa_target_bt_4 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_4.setGeometry(QtCore.QRect(120, 200, 31, 31))
        self.fa_target_bt_4.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_4.setText("")
        self.fa_target_bt_4.setObjectName("fa_target_bt_4")
        self.fa_target_bt_5 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_5.setGeometry(QtCore.QRect(30, 210, 31, 31))
        self.fa_target_bt_5.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_5.setText("")
        self.fa_target_bt_5.setObjectName("fa_target_bt_5")
        self.fa_target_bt_6 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_6.setGeometry(QtCore.QRect(120, 280, 31, 31))
        self.fa_target_bt_6.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_6.setText("")
        self.fa_target_bt_6.setObjectName("fa_target_bt_6")
        self.fa_target_bt_7 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_7.setGeometry(QtCore.QRect(40, 290, 31, 31))
        self.fa_target_bt_7.setStyleSheet("background-color:#123123;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_7.setText("")
        self.fa_target_bt_7.setObjectName("fa_target_bt_7")
        self.fa_target_bt_8 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_8.setGeometry(QtCore.QRect(130, 340, 31, 31))
        self.fa_target_bt_8.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_8.setText("")
        self.fa_target_bt_8.setObjectName("fa_target_bt_8")
        self.fa_target_bt_9 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_9.setGeometry(QtCore.QRect(40, 350, 31, 31))
        self.fa_target_bt_9.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_9.setText("")
        self.fa_target_bt_9.setObjectName("fa_target_bt_9")
        self.fa_target_bt_10 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_10.setGeometry(QtCore.QRect(180, 210, 31, 31))
        self.fa_target_bt_10.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_10.setText("")
        self.fa_target_bt_10.setObjectName("fa_target_bt_10")
        self.fa_target_bt_11 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_11.setGeometry(QtCore.QRect(280, 340, 31, 31))
        self.fa_target_bt_11.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_11.setText("")
        self.fa_target_bt_11.setObjectName("fa_target_bt_11")
        self.fa_target_bt_12 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_12.setGeometry(QtCore.QRect(190, 290, 31, 31))
        self.fa_target_bt_12.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_12.setText("")
        self.fa_target_bt_12.setObjectName("fa_target_bt_12")
        self.fa_target_bt_13 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_13.setGeometry(QtCore.QRect(270, 280, 31, 31))
        self.fa_target_bt_13.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_13.setText("")
        self.fa_target_bt_13.setObjectName("fa_target_bt_13")
        self.fa_target_bt_14 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_14.setGeometry(QtCore.QRect(270, 140, 31, 31))
        self.fa_target_bt_14.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_14.setText("")
        self.fa_target_bt_14.setObjectName("fa_target_bt_14")
        self.fa_target_bt_15 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_15.setGeometry(QtCore.QRect(270, 200, 31, 31))
        self.fa_target_bt_15.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_15.setText("")
        self.fa_target_bt_15.setObjectName("fa_target_bt_15")
        self.fa_target_bt_16 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_16.setGeometry(QtCore.QRect(180, 130, 31, 31))
        self.fa_target_bt_16.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_16.setText("")
        self.fa_target_bt_16.setObjectName("fa_target_bt_16")
        self.fa_target_bt_17 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_17.setGeometry(QtCore.QRect(190, 350, 31, 31))
        self.fa_target_bt_17.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_17.setText("")
        self.fa_target_bt_17.setObjectName("fa_target_bt_17")
        self.fa_target_bt_18 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_18.setGeometry(QtCore.QRect(460, 330, 31, 31))
        self.fa_target_bt_18.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_18.setText("")
        self.fa_target_bt_18.setObjectName("fa_target_bt_18")
        self.fa_target_bt_19 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_19.setGeometry(QtCore.QRect(450, 270, 31, 31))
        self.fa_target_bt_19.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_19.setText("")
        self.fa_target_bt_19.setObjectName("fa_target_bt_19")
        self.fa_target_bt_20 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_20.setGeometry(QtCore.QRect(360, 120, 31, 31))
        self.fa_target_bt_20.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_20.setText("")
        self.fa_target_bt_20.setObjectName("fa_target_bt_20")
        self.fa_target_bt_21 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_21.setGeometry(QtCore.QRect(370, 340, 31, 31))
        self.fa_target_bt_21.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_21.setText("")
        self.fa_target_bt_21.setObjectName("fa_target_bt_21")
        self.fa_target_bt_22 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_22.setGeometry(QtCore.QRect(370, 280, 31, 31))
        self.fa_target_bt_22.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_22.setText("")
        self.fa_target_bt_22.setObjectName("fa_target_bt_22")
        self.fa_target_bt_23 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_23.setGeometry(QtCore.QRect(450, 130, 31, 31))
        self.fa_target_bt_23.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_23.setText("")
        self.fa_target_bt_23.setObjectName("fa_target_bt_23")
        self.fa_target_bt_24 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_24.setGeometry(QtCore.QRect(360, 200, 31, 31))
        self.fa_target_bt_24.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_24.setText("")
        self.fa_target_bt_24.setObjectName("fa_target_bt_24")
        self.fa_target_bt_25 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_25.setGeometry(QtCore.QRect(450, 190, 31, 31))
        self.fa_target_bt_25.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_25.setText("")
        self.fa_target_bt_25.setObjectName("fa_target_bt_25")
        self.fa_target_bt_26 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_26.setGeometry(QtCore.QRect(520, 200, 31, 31))
        self.fa_target_bt_26.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_26.setText("")
        self.fa_target_bt_26.setObjectName("fa_target_bt_26")
        self.fa_target_bt_27 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_27.setGeometry(QtCore.QRect(620, 330, 31, 31))
        self.fa_target_bt_27.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_27.setText("")
        self.fa_target_bt_27.setObjectName("fa_target_bt_27")
        self.fa_target_bt_28 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_28.setGeometry(QtCore.QRect(530, 280, 31, 31))
        self.fa_target_bt_28.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_28.setText("")
        self.fa_target_bt_28.setObjectName("fa_target_bt_28")
        self.fa_target_bt_29 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_29.setGeometry(QtCore.QRect(610, 270, 31, 31))
        self.fa_target_bt_29.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_29.setText("")
        self.fa_target_bt_29.setObjectName("fa_target_bt_29")
        self.fa_target_bt_30 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_30.setGeometry(QtCore.QRect(610, 130, 31, 31))
        self.fa_target_bt_30.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_30.setText("")
        self.fa_target_bt_30.setObjectName("fa_target_bt_30")
        self.fa_target_bt_31 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_31.setGeometry(QtCore.QRect(610, 190, 31, 31))
        self.fa_target_bt_31.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_31.setText("")
        self.fa_target_bt_31.setObjectName("fa_target_bt_31")
        self.fa_target_bt_32 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_32.setGeometry(QtCore.QRect(520, 120, 31, 31))
        self.fa_target_bt_32.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_32.setText("")
        self.fa_target_bt_32.setObjectName("fa_target_bt_32")
        self.fa_target_bt_33 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_33.setGeometry(QtCore.QRect(530, 340, 31, 31))
        self.fa_target_bt_33.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_33.setText("")
        self.fa_target_bt_33.setObjectName("fa_target_bt_33")
        self.fa_target_bt_34 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_34.setGeometry(QtCore.QRect(670, 200, 31, 31))
        self.fa_target_bt_34.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_34.setText("")
        self.fa_target_bt_34.setObjectName("fa_target_bt_34")
        self.fa_target_bt_35 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_35.setGeometry(QtCore.QRect(770, 330, 31, 31))
        self.fa_target_bt_35.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_35.setText("")
        self.fa_target_bt_35.setObjectName("fa_target_bt_35")
        self.fa_target_bt_36 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_36.setGeometry(QtCore.QRect(680, 280, 31, 31))
        self.fa_target_bt_36.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_36.setText("")
        self.fa_target_bt_36.setObjectName("fa_target_bt_36")
        self.fa_target_bt_37 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_37.setGeometry(QtCore.QRect(760, 270, 31, 31))
        self.fa_target_bt_37.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_37.setText("")
        self.fa_target_bt_37.setObjectName("fa_target_bt_37")
        self.fa_target_bt_38 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_38.setGeometry(QtCore.QRect(760, 130, 31, 31))
        self.fa_target_bt_38.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_38.setText("")
        self.fa_target_bt_38.setObjectName("fa_target_bt_38")
        self.fa_target_bt_39 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_39.setGeometry(QtCore.QRect(760, 190, 31, 31))
        self.fa_target_bt_39.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_39.setText("")
        self.fa_target_bt_39.setObjectName("fa_target_bt_39")
        self.fa_target_bt_40 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_40.setGeometry(QtCore.QRect(670, 120, 31, 31))
        self.fa_target_bt_40.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_40.setText("")
        self.fa_target_bt_40.setObjectName("fa_target_bt_40")
        self.fa_target_bt_41 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_41.setGeometry(QtCore.QRect(680, 340, 31, 31))
        self.fa_target_bt_41.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_41.setText("")
        self.fa_target_bt_41.setObjectName("fa_target_bt_41")
        self.timer = QtWidgets.QLabel(self.centralwidget)
        self.timer.setGeometry(QtCore.QRect(20, 20, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(16)
        self.timer.setFont(font)
        self.timer.setObjectName("timer")
        self.count_lal = QtWidgets.QLabel(self.centralwidget)
        self.count_lal.setGeometry(QtCore.QRect(680, 20, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(16)
        self.count_lal.setFont(font)
        self.count_lal.setObjectName("count_lal")
        self.fa_target_bt_42 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_42.setGeometry(QtCore.QRect(270, 220, 31, 31))
        self.fa_target_bt_42.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_42.setText("")
        self.fa_target_bt_42.setObjectName("fa_target_bt_42")
        self.fa_target_bt_43 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_43.setGeometry(QtCore.QRect(120, 220, 31, 31))
        self.fa_target_bt_43.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_43.setText("")
        self.fa_target_bt_43.setObjectName("fa_target_bt_43")
        self.fa_target_bt_44 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_44.setGeometry(QtCore.QRect(450, 210, 31, 31))
        self.fa_target_bt_44.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_44.setText("")
        self.fa_target_bt_44.setObjectName("fa_target_bt_44")
        self.fa_target_bt_45 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_45.setGeometry(QtCore.QRect(370, 360, 31, 31))
        self.fa_target_bt_45.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_45.setText("")
        self.fa_target_bt_45.setObjectName("fa_target_bt_45")
        self.fa_target_bt_46 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_46.setGeometry(QtCore.QRect(610, 210, 31, 31))
        self.fa_target_bt_46.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_46.setText("")
        self.fa_target_bt_46.setObjectName("fa_target_bt_46")
        self.fa_target_bt_47 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_47.setGeometry(QtCore.QRect(770, 410, 31, 31))
        self.fa_target_bt_47.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_47.setText("")
        self.fa_target_bt_47.setObjectName("fa_target_bt_47")
        self.fa_target_bt_48 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_48.setGeometry(QtCore.QRect(610, 350, 31, 31))
        self.fa_target_bt_48.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_48.setText("")
        self.fa_target_bt_48.setObjectName("fa_target_bt_48")
        self.fa_target_bt_49 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_49.setGeometry(QtCore.QRect(450, 350, 31, 31))
        self.fa_target_bt_49.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_49.setText("")
        self.fa_target_bt_49.setObjectName("fa_target_bt_49")
        self.fa_target_bt_50 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_50.setGeometry(QtCore.QRect(370, 420, 31, 31))
        self.fa_target_bt_50.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_50.setText("")
        self.fa_target_bt_50.setObjectName("fa_target_bt_50")
        self.fa_target_bt_51 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_51.setGeometry(QtCore.QRect(190, 430, 31, 31))
        self.fa_target_bt_51.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_51.setText("")
        self.fa_target_bt_51.setObjectName("fa_target_bt_51")
        self.fa_target_bt_52 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_52.setGeometry(QtCore.QRect(530, 420, 31, 31))
        self.fa_target_bt_52.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_52.setText("")
        self.fa_target_bt_52.setObjectName("fa_target_bt_52")
        self.fa_target_bt_53 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_53.setGeometry(QtCore.QRect(190, 370, 31, 31))
        self.fa_target_bt_53.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_53.setText("")
        self.fa_target_bt_53.setObjectName("fa_target_bt_53")
        self.fa_target_bt_54 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_54.setGeometry(QtCore.QRect(670, 200, 31, 31))
        self.fa_target_bt_54.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_54.setText("")
        self.fa_target_bt_54.setObjectName("fa_target_bt_54")
        self.fa_target_bt_55 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_55.setGeometry(QtCore.QRect(270, 280, 31, 31))
        self.fa_target_bt_55.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_55.setText("")
        self.fa_target_bt_55.setObjectName("fa_target_bt_55")
        self.fa_target_bt_56 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_56.setGeometry(QtCore.QRect(40, 370, 31, 31))
        self.fa_target_bt_56.setStyleSheet("background-color:#123123;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_56.setText("")
        self.fa_target_bt_56.setObjectName("fa_target_bt_56")
        self.fa_target_bt_57 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_57.setGeometry(QtCore.QRect(760, 270, 31, 31))
        self.fa_target_bt_57.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_57.setText("")
        self.fa_target_bt_57.setObjectName("fa_target_bt_57")
        self.fa_target_bt_58 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_58.setGeometry(QtCore.QRect(130, 420, 31, 31))
        self.fa_target_bt_58.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_58.setText("")
        self.fa_target_bt_58.setObjectName("fa_target_bt_58")
        self.fa_target_bt_59 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_59.setGeometry(QtCore.QRect(670, 280, 31, 31))
        self.fa_target_bt_59.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_59.setText("")
        self.fa_target_bt_59.setObjectName("fa_target_bt_59")
        self.fa_target_bt_60 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_60.setGeometry(QtCore.QRect(620, 410, 31, 31))
        self.fa_target_bt_60.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_60.setText("")
        self.fa_target_bt_60.setObjectName("fa_target_bt_60")
        self.fa_target_bt_61 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_61.setGeometry(QtCore.QRect(680, 420, 31, 31))
        self.fa_target_bt_61.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_61.setText("")
        self.fa_target_bt_61.setObjectName("fa_target_bt_61")
        self.fa_target_bt_62 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_62.setGeometry(QtCore.QRect(360, 280, 31, 31))
        self.fa_target_bt_62.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_62.setText("")
        self.fa_target_bt_62.setObjectName("fa_target_bt_62")
        self.fa_target_bt_63 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_63.setGeometry(QtCore.QRect(610, 270, 31, 31))
        self.fa_target_bt_63.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_63.setText("")
        self.fa_target_bt_63.setObjectName("fa_target_bt_63")
        self.fa_target_bt_64 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_64.setGeometry(QtCore.QRect(760, 350, 31, 31))
        self.fa_target_bt_64.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_64.setText("")
        self.fa_target_bt_64.setObjectName("fa_target_bt_64")
        self.fa_target_bt_65 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_65.setGeometry(QtCore.QRect(120, 280, 31, 31))
        self.fa_target_bt_65.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_65.setText("")
        self.fa_target_bt_65.setObjectName("fa_target_bt_65")
        self.fa_target_bt_66 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_66.setGeometry(QtCore.QRect(180, 210, 31, 31))
        self.fa_target_bt_66.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_66.setText("")
        self.fa_target_bt_66.setObjectName("fa_target_bt_66")
        self.fa_target_bt_67 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_67.setGeometry(QtCore.QRect(120, 360, 31, 31))
        self.fa_target_bt_67.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_67.setText("")
        self.fa_target_bt_67.setObjectName("fa_target_bt_67")
        self.fa_target_bt_68 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_68.setGeometry(QtCore.QRect(270, 360, 31, 31))
        self.fa_target_bt_68.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_68.setText("")
        self.fa_target_bt_68.setObjectName("fa_target_bt_68")
        self.fa_target_bt_69 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_69.setGeometry(QtCore.QRect(180, 290, 31, 31))
        self.fa_target_bt_69.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_69.setText("")
        self.fa_target_bt_69.setObjectName("fa_target_bt_69")
        self.fa_target_bt_70 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_70.setGeometry(QtCore.QRect(520, 280, 31, 31))
        self.fa_target_bt_70.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_70.setText("")
        self.fa_target_bt_70.setObjectName("fa_target_bt_70")
        self.fa_target_bt_71 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_71.setGeometry(QtCore.QRect(30, 210, 31, 31))
        self.fa_target_bt_71.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_71.setText("")
        self.fa_target_bt_71.setObjectName("fa_target_bt_71")
        self.fa_target_bt_72 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_72.setGeometry(QtCore.QRect(450, 270, 31, 31))
        self.fa_target_bt_72.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_72.setText("")
        self.fa_target_bt_72.setObjectName("fa_target_bt_72")
        self.fa_target_bt_73 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_73.setGeometry(QtCore.QRect(280, 420, 31, 31))
        self.fa_target_bt_73.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_73.setText("")
        self.fa_target_bt_73.setObjectName("fa_target_bt_73")
        self.fa_target_bt_74 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_74.setGeometry(QtCore.QRect(30, 290, 31, 31))
        self.fa_target_bt_74.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_74.setText("")
        self.fa_target_bt_74.setObjectName("fa_target_bt_74")
        self.fa_target_bt_75 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_75.setGeometry(QtCore.QRect(360, 200, 31, 31))
        self.fa_target_bt_75.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_75.setText("")
        self.fa_target_bt_75.setObjectName("fa_target_bt_75")
        self.fa_target_bt_76 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_76.setGeometry(QtCore.QRect(520, 200, 31, 31))
        self.fa_target_bt_76.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_76.setText("")
        self.fa_target_bt_76.setObjectName("fa_target_bt_76")
        self.fa_target_bt_77 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_77.setGeometry(QtCore.QRect(40, 430, 31, 31))
        self.fa_target_bt_77.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_77.setText("")
        self.fa_target_bt_77.setObjectName("fa_target_bt_77")
        self.fa_target_bt_78 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_78.setGeometry(QtCore.QRect(680, 360, 31, 31))
        self.fa_target_bt_78.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_78.setText("")
        self.fa_target_bt_78.setObjectName("fa_target_bt_78")
        self.fa_target_bt_79 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_79.setGeometry(QtCore.QRect(530, 360, 31, 31))
        self.fa_target_bt_79.setStyleSheet("background-color:#BA68C8;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_79.setText("")
        self.fa_target_bt_79.setObjectName("fa_target_bt_79")
        self.fa_target_bt_80 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_80.setGeometry(QtCore.QRect(460, 410, 31, 31))
        self.fa_target_bt_80.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_80.setText("")
        self.fa_target_bt_80.setObjectName("fa_target_bt_80")
        self.fa_target_bt_81 = QtWidgets.QPushButton(self.centralwidget)
        self.fa_target_bt_81.setGeometry(QtCore.QRect(760, 210, 31, 31))
        self.fa_target_bt_81.setStyleSheet("background-color:#E6EE9C;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.fa_target_bt_81.setText("")
        self.fa_target_bt_81.setObjectName("fa_target_bt_81")
        self.fa_target_bt_2.raise_()
        self.fa_target_bt_3.raise_()
        self.fa_target_bt_4.raise_()
        self.fa_target_bt_5.raise_()
        self.fa_target_bt_6.raise_()
        self.fa_target_bt_7.raise_()
        self.fa_target_bt_8.raise_()
        self.fa_target_bt_9.raise_()
        self.fa_target_bt_10.raise_()
        self.fa_target_bt_11.raise_()
        self.fa_target_bt_12.raise_()
        self.fa_target_bt_13.raise_()
        self.fa_target_bt_14.raise_()
        self.fa_target_bt_15.raise_()
        self.fa_target_bt_16.raise_()
        self.fa_target_bt_17.raise_()
        self.fa_target_bt_18.raise_()
        self.fa_target_bt_19.raise_()
        self.fa_target_bt_20.raise_()
        self.fa_target_bt_21.raise_()
        self.fa_target_bt_22.raise_()
        self.fa_target_bt_23.raise_()
        self.fa_target_bt_24.raise_()
        self.fa_target_bt_25.raise_()
        self.fa_target_bt_26.raise_()
        self.fa_target_bt_27.raise_()
        self.fa_target_bt_28.raise_()
        self.fa_target_bt_29.raise_()
        self.fa_target_bt_30.raise_()
        self.fa_target_bt_31.raise_()
        self.fa_target_bt_32.raise_()
        self.fa_target_bt_33.raise_()
        self.fa_target_bt_34.raise_()
        self.fa_target_bt_35.raise_()
        self.fa_target_bt_36.raise_()
        self.fa_target_bt_37.raise_()
        self.fa_target_bt_38.raise_()
        self.fa_target_bt_39.raise_()
        self.fa_target_bt_40.raise_()
        self.fa_target_bt_41.raise_()
        self.timer.raise_()
        self.count_lal.raise_()
        self.fa_target_bt_42.raise_()
        self.fa_target_bt_43.raise_()
        self.fa_target_bt_44.raise_()
        self.fa_target_bt_45.raise_()
        self.fa_target_bt_46.raise_()
        self.fa_target_bt_47.raise_()
        self.fa_target_bt_48.raise_()
        self.fa_target_bt_49.raise_()
        self.fa_target_bt_50.raise_()
        self.fa_target_bt_51.raise_()
        self.fa_target_bt_52.raise_()
        self.fa_target_bt_53.raise_()
        self.fa_target_bt_54.raise_()
        self.fa_target_bt_55.raise_()
        self.fa_target_bt_56.raise_()
        self.fa_target_bt_57.raise_()
        self.fa_target_bt_58.raise_()
        self.fa_target_bt_59.raise_()
        self.fa_target_bt_60.raise_()
        self.fa_target_bt_61.raise_()
        self.fa_target_bt_62.raise_()
        self.fa_target_bt_63.raise_()
        self.fa_target_bt_64.raise_()
        self.fa_target_bt_65.raise_()
        self.fa_target_bt_66.raise_()
        self.fa_target_bt_67.raise_()
        self.fa_target_bt_68.raise_()
        self.fa_target_bt_69.raise_()
        self.fa_target_bt_70.raise_()
        self.fa_target_bt_71.raise_()
        self.fa_target_bt_72.raise_()
        self.fa_target_bt_73.raise_()
        self.fa_target_bt_74.raise_()
        self.fa_target_bt_75.raise_()
        self.fa_target_bt_76.raise_()
        self.fa_target_bt_77.raise_()
        self.fa_target_bt_78.raise_()
        self.fa_target_bt_79.raise_()
        self.fa_target_bt_80.raise_()
        self.fa_target_bt_81.raise_()
        self.target_bt.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.target_bt.setText(_translate("MainWindow", "TARGET"))
        self.timer.setText(_translate("MainWindow", "0000"))
        self.count_lal.setText(_translate("MainWindow", "0"))
