# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'howtoplay_reaction.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(665, 391)
        Form.setMinimumSize(QtCore.QSize(665, 391))
        Form.setMaximumSize(QtCore.QSize(665, 16777215))
        self.volume_ll_2 = QtWidgets.QLabel(Form)
        self.volume_ll_2.setGeometry(QtCore.QRect(70, 200, 541, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(16)
        self.volume_ll_2.setFont(font)
        self.volume_ll_2.setStyleSheet("color: white;\n"
"background-color: #FFC107;\n"
"border-style: outset;\n"
"border-radius:10px;\n"
"")
        self.volume_ll_2.setObjectName("volume_ll_2")
        self.volume_ll = QtWidgets.QLabel(Form)
        self.volume_ll.setGeometry(QtCore.QRect(70, 110, 541, 111))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(16)
        self.volume_ll.setFont(font)
        self.volume_ll.setStyleSheet("color: white;\n"
"background-color: #FFC107;\n"
"border-style: outset;\n"
"border-radius:10px;\n"
"")
        self.volume_ll.setObjectName("volume_ll")
        self.start_bt = QtWidgets.QPushButton(Form)
        self.start_bt.setGeometry(QtCore.QRect(220, 300, 241, 81))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.start_bt.setFont(font)
        self.start_bt.setStyleSheet("background-color:#8BC34A;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.start_bt.setObjectName("start_bt")
        self.quick_math_bt_2 = QtWidgets.QPushButton(Form)
        self.quick_math_bt_2.setGeometry(QtCore.QRect(200, 20, 271, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.quick_math_bt_2.setFont(font)
        self.quick_math_bt_2.setStyleSheet("background-color:#8BC34A;\n"
"color:white;\n"
"border-style: outset;\n"
"border-radius:10px;")
        self.quick_math_bt_2.setObjectName("quick_math_bt_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.volume_ll_2.setText(_translate("Form", "You have 10 seconds to each"))
        self.volume_ll.setText(_translate("Form", "You need to hit a light red button with text on"))
        self.start_bt.setText(_translate("Form", "START"))
        self.quick_math_bt_2.setText(_translate("Form", "Reaction"))
