# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oh_noo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 400)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(140, 20, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(100, 140, 191, 191))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(r"Pictures/pngtree-wrong-false-icon-design-template-vector-isolated-png-image_711430 (1).jpg"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(90, 80, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.try_again_bt = QtWidgets.QPushButton(Dialog)
        self.try_again_bt.setGeometry(QtCore.QRect(80, 350, 75, 23))
        self.try_again_bt.setObjectName("try_again_bt")
        self.quit_bt = QtWidgets.QPushButton(Dialog)
        self.quit_bt.setGeometry(QtCore.QRect(240, 350, 75, 23))
        self.quit_bt.setObjectName("quit_bt")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Oh no!"))
        self.label_3.setText(_translate("Dialog", "You didn\'t do it"))
        self.try_again_bt.setText(_translate("Dialog", "Try Again"))
        self.quit_bt.setText(_translate("Dialog", "Exit"))
