# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spatialmem.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(886, 837)
        MainWindow.setMinimumSize(QtCore.QSize(886, 837))
        MainWindow.setMaximumSize(QtCore.QSize(886, 837))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(90, 60, 100, 100))
        self.pushButton_1.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 170, 100, 100))
        self.pushButton_2.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(90, 500, 100, 100))
        self.pushButton_3.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(90, 390, 100, 100))
        self.pushButton_4.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(90, 610, 100, 100))
        self.pushButton_5.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(90, 280, 100, 100))
        self.pushButton_6.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(210, 500, 100, 100))
        self.pushButton_7.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(210, 280, 100, 100))
        self.pushButton_8.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(210, 60, 100, 100))
        self.pushButton_9.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(210, 390, 100, 100))
        self.pushButton_10.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(210, 610, 100, 100))
        self.pushButton_11.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(210, 170, 100, 100))
        self.pushButton_12.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(330, 500, 100, 100))
        self.pushButton_13.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(330, 280, 100, 100))
        self.pushButton_14.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(330, 60, 100, 100))
        self.pushButton_15.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(330, 390, 100, 100))
        self.pushButton_16.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(330, 610, 100, 100))
        self.pushButton_17.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(330, 170, 100, 100))
        self.pushButton_18.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(690, 60, 100, 100))
        self.pushButton_19.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(690, 390, 100, 100))
        self.pushButton_20.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(570, 390, 100, 100))
        self.pushButton_21.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(570, 170, 100, 100))
        self.pushButton_22.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(450, 170, 100, 100))
        self.pushButton_23.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_24.setGeometry(QtCore.QRect(450, 60, 100, 100))
        self.pushButton_24.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_25.setGeometry(QtCore.QRect(690, 170, 100, 100))
        self.pushButton_25.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_26.setGeometry(QtCore.QRect(450, 500, 100, 100))
        self.pushButton_26.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_27.setGeometry(QtCore.QRect(450, 610, 100, 100))
        self.pushButton_27.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_28.setGeometry(QtCore.QRect(570, 610, 100, 100))
        self.pushButton_28.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_29.setGeometry(QtCore.QRect(450, 390, 100, 100))
        self.pushButton_29.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_30.setGeometry(QtCore.QRect(570, 60, 100, 100))
        self.pushButton_30.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_31.setGeometry(QtCore.QRect(450, 280, 100, 100))
        self.pushButton_31.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_32.setGeometry(QtCore.QRect(690, 610, 100, 100))
        self.pushButton_32.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_33 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_33.setGeometry(QtCore.QRect(570, 500, 100, 100))
        self.pushButton_33.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_34 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_34.setGeometry(QtCore.QRect(570, 280, 100, 100))
        self.pushButton_34.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_35 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_35.setGeometry(QtCore.QRect(690, 280, 100, 100))
        self.pushButton_35.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_36 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_36.setGeometry(QtCore.QRect(690, 500, 100, 100))
        self.pushButton_36.setStyleSheet("background-color: #8BC34A;\n"
"color: Transparent\n"
"")
        self.pushButton_36.setObjectName("pushButton_36")
        self.count_lal = QtWidgets.QLabel(self.centralwidget)
        self.count_lal.setGeometry(QtCore.QRect(440, 10, 47, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(16)
        self.count_lal.setFont(font)
        self.count_lal.setObjectName("count_lal")
        self.okay_byt = QtWidgets.QPushButton(self.centralwidget)
        self.okay_byt.setGeometry(QtCore.QRect(400, 710, 76, 76))
        self.okay_byt.setCheckable(False)
        self.okay_byt.setObjectName("okay_byt")
        self.timer = QtWidgets.QLabel(self.centralwidget)
        self.timer.setGeometry(QtCore.QRect(20, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(16)
        self.timer.setFont(font)
        self.timer.setObjectName("timer")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 886, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_10.setText(_translate("MainWindow", "10"))
        self.pushButton_11.setText(_translate("MainWindow", "11"))
        self.pushButton_12.setText(_translate("MainWindow", "12"))
        self.pushButton_13.setText(_translate("MainWindow", "13"))
        self.pushButton_14.setText(_translate("MainWindow", "14"))
        self.pushButton_15.setText(_translate("MainWindow", "15"))
        self.pushButton_16.setText(_translate("MainWindow", "16"))
        self.pushButton_17.setText(_translate("MainWindow", "17"))
        self.pushButton_18.setText(_translate("MainWindow", "18"))
        self.pushButton_19.setText(_translate("MainWindow", "19"))
        self.pushButton_20.setText(_translate("MainWindow", "20"))
        self.pushButton_21.setText(_translate("MainWindow", "21"))
        self.pushButton_22.setText(_translate("MainWindow", "22"))
        self.pushButton_23.setText(_translate("MainWindow", "23"))
        self.pushButton_24.setText(_translate("MainWindow", "24"))
        self.pushButton_25.setText(_translate("MainWindow", "25"))
        self.pushButton_26.setText(_translate("MainWindow", "26"))
        self.pushButton_27.setText(_translate("MainWindow", "27"))
        self.pushButton_28.setText(_translate("MainWindow", "28"))
        self.pushButton_29.setText(_translate("MainWindow", "29"))
        self.pushButton_30.setText(_translate("MainWindow", "30"))
        self.pushButton_31.setText(_translate("MainWindow", "31"))
        self.pushButton_32.setText(_translate("MainWindow", "32"))
        self.pushButton_33.setText(_translate("MainWindow", "33"))
        self.pushButton_34.setText(_translate("MainWindow", "34"))
        self.pushButton_35.setText(_translate("MainWindow", "35"))
        self.pushButton_36.setText(_translate("MainWindow", "36"))
        self.count_lal.setText(_translate("MainWindow", "0"))
        self.okay_byt.setText(_translate("MainWindow", "Okay"))
        self.timer.setText(_translate("MainWindow", "00:00"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
